name: minecraft-stack

volumes:
  minecraft-data:
  backup-data:

services:
  manager:
    build:
      context: .
      dockerfile: Manager/Dockerfile
    container_name: minecraft-manager
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      RCON_HOST: minecraft-server
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      MC_DATA_DIR: "/data"
    volumes:
      - minecraft-data:/data
      - ./resources:/app/resources:ro
      - backup-data:/app/backups
    depends_on:
      minecraft:
        condition: service_healthy
    restart: unless-stopped
      
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft-server
    ports:
      - "25565:25565" # Minecraft
      - "24454:24454/udp" # VoiceChat
      - "25575:25575" # RCON
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      # https://www.curseforge.com/minecraft/modpacks/strictly-medieval-3-forge/files/5778153
      CF_API_KEY: "${CF_API_KEY}"
      CF_MODPACK_SLUG: "strictly-medieval-3-forge"
      CF_MODPACK_FILE_ID: "5778153"
      MEMORY: "12G"
      VERSION: "1.19.2"
      MODS: |
        /resources/voicechat-forge-1.19.2-2.6.2.jar
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "25575"
      # Additional settings for better performance
      ENABLE_RCON: "true"
      BROADCAST_RCON_TO_OPS: "true"
      MAX_PLAYERS: "4"
      DIFFICULTY: "hard"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "false"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      MAX_BUILD_HEIGHT: "256"
      MAX_WORLD_SIZE: "29999984"
      PVP: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      VIEW_DISTANCE: "10"
    volumes:
      - minecraft-data:/data
      - ./resources:/resources:ro
    healthcheck:
      test: ["CMD", "mc-monitor", "status", "--host", "localhost", "--port", "25565"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s
    restart: unless-stopped